### PR TITLE
Create Motor-stand.md

### PR DESCRIPTION
**Pull request by bcpickett42**

### CODE REVIEW

**Review by JesseTNRoberts — COMMENTED** [review]
The constraints of the system need to be precise and measurable.

**Review by JesseTNRoberts — COMMENTED** [review]
this won't work. D clamps on a pipe that sits on the floor isn't going to actually function.

**Review by JesseTNRoberts — COMMENTED** [review]
use headings to give organization.

**Comment by rjdurlin42** [comment]
> this won't work. D clamps on a pipe that sits on the floor isn't going to actually function.

**Comment by bcpickett42** [comment]
> this won't work. D clamps on a pipe that sits on the floor isn't going to actually function.

**Review by JesseTNRoberts — APPROVED** [review]

**Pull request merged**
